blank_issues_enabled: false
contact_links:
  - name: 💡 Feature Request
    url: https://github.com/metafoxapp/metafox-issues/discussions/new?category=ideas
    about: If you've got an idea for a new feature in React Router, please open a new Discussion with the `Proposals` label
  - name: 🤔 Usage Question (Github Discussions)
    url: https://github.com/metafoxapp/metafox-issues/discussions/new?category=q-a
    about: Open a Discussion in GitHub wih the `Q&A` label
  
